default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ig_clone_app_development







test:
  <<: *default
  database: ig_clone_app_test

production:
  <<: *default
  database: ig_clone_app_production
  username: ig_clone_app
  password: <%= ENV['IG_CLONE_APP_DATABASE_PASSWORD'] %>
